// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drawings.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createDrawing = `-- name: CreateDrawing :one
INSERT INTO drawings (match_id, user_id, doodle_strokes, finished_strokes)
VALUES ($1, $2, $3, $4)
RETURNING id, match_id, user_id, doodle_strokes, finished_strokes, vote_count, created_at
`

type CreateDrawingParams struct {
	MatchID         uuid.UUID
	UserID          uuid.NullUUID
	DoodleStrokes   json.RawMessage
	FinishedStrokes json.RawMessage
}

func (q *Queries) CreateDrawing(ctx context.Context, arg CreateDrawingParams) (Drawing, error) {
	row := q.db.QueryRowContext(ctx, createDrawing,
		arg.MatchID,
		arg.UserID,
		arg.DoodleStrokes,
		arg.FinishedStrokes,
	)
	var i Drawing
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.DoodleStrokes,
		&i.FinishedStrokes,
		&i.VoteCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDrawingByMatchID = `-- name: DeleteDrawingByMatchID :exec
DELETE FROM drawings WHERE match_id = $1
`

func (q *Queries) DeleteDrawingByMatchID(ctx context.Context, matchID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDrawingByMatchID, matchID)
	return err
}

const getDrawingsByMatchID = `-- name: GetDrawingsByMatchID :many
SELECT id, match_id, user_id, doodle_strokes, finished_strokes, vote_count, created_at FROM drawings
WHERE match_id = $1
`

func (q *Queries) GetDrawingsByMatchID(ctx context.Context, matchID uuid.UUID) ([]Drawing, error) {
	rows, err := q.db.QueryContext(ctx, getDrawingsByMatchID, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drawing
	for rows.Next() {
		var i Drawing
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.UserID,
			&i.DoodleStrokes,
			&i.FinishedStrokes,
			&i.VoteCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDrawingsByUserID = `-- name: GetDrawingsByUserID :many
SELECT match_id, finished_strokes, created_at
FROM drawings
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 20 OFFSET $2
`

type GetDrawingsByUserIDParams struct {
	UserID uuid.NullUUID
	Offset int32
}

type GetDrawingsByUserIDRow struct {
	MatchID         uuid.UUID
	FinishedStrokes json.RawMessage
	CreatedAt       sql.NullTime
}

func (q *Queries) GetDrawingsByUserID(ctx context.Context, arg GetDrawingsByUserIDParams) ([]GetDrawingsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getDrawingsByUserID, arg.UserID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDrawingsByUserIDRow
	for rows.Next() {
		var i GetDrawingsByUserIDRow
		if err := rows.Scan(&i.MatchID, &i.FinishedStrokes, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostRecentDrawings = `-- name: GetMostRecentDrawings :many
SELECT id, match_id, user_id, doodle_strokes, finished_strokes, vote_count, created_at
FROM drawings
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetMostRecentDrawingsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetMostRecentDrawings(ctx context.Context, arg GetMostRecentDrawingsParams) ([]Drawing, error) {
	rows, err := q.db.QueryContext(ctx, getMostRecentDrawings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drawing
	for rows.Next() {
		var i Drawing
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.UserID,
			&i.DoodleStrokes,
			&i.FinishedStrokes,
			&i.VoteCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostVotedDrawings = `-- name: GetMostVotedDrawings :many
SELECT id, match_id, user_id, doodle_strokes, finished_strokes, vote_count, created_at
FROM drawings
WHERE created_at > NOW() - INTERVAL '1 day' * $3
ORDER BY vote_count DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type GetMostVotedDrawingsParams struct {
	Limit         int32
	Offset        int32
	TimeframeDays interface{}
}

func (q *Queries) GetMostVotedDrawings(ctx context.Context, arg GetMostVotedDrawingsParams) ([]Drawing, error) {
	rows, err := q.db.QueryContext(ctx, getMostVotedDrawings, arg.Limit, arg.Offset, arg.TimeframeDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drawing
	for rows.Next() {
		var i Drawing
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.UserID,
			&i.DoodleStrokes,
			&i.FinishedStrokes,
			&i.VoteCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrawingFinished = `-- name: UpdateDrawingFinished :exec
UPDATE drawings
SET finished_strokes = $1
WHERE match_id = $2 AND user_id = $3
`

type UpdateDrawingFinishedParams struct {
	FinishedStrokes json.RawMessage
	MatchID         uuid.UUID
	UserID          uuid.NullUUID
}

func (q *Queries) UpdateDrawingFinished(ctx context.Context, arg UpdateDrawingFinishedParams) error {
	_, err := q.db.ExecContext(ctx, updateDrawingFinished, arg.FinishedStrokes, arg.MatchID, arg.UserID)
	return err
}
