// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drawings.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createDrawing = `-- name: CreateDrawing :one
INSERT INTO drawings (match_id, starter_id, finisher_id, doodle_strokes, finished_strokes)
VALUES (
	$1,
	$2,
	$3,
    $4,
    $5
)
RETURNING id, match_id, starter_id, finisher_id, doodle_strokes, finished_strokes, vote_count, created_at, finished_at
`

type CreateDrawingParams struct {
	MatchID         uuid.UUID
	StarterID       uuid.UUID
	FinisherID      uuid.UUID
	DoodleStrokes   json.RawMessage
	FinishedStrokes json.RawMessage
}

func (q *Queries) CreateDrawing(ctx context.Context, arg CreateDrawingParams) (Drawing, error) {
	row := q.db.QueryRowContext(ctx, createDrawing,
		arg.MatchID,
		arg.StarterID,
		arg.FinisherID,
		arg.DoodleStrokes,
		arg.FinishedStrokes,
	)
	var i Drawing
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.StarterID,
		&i.FinisherID,
		&i.DoodleStrokes,
		&i.FinishedStrokes,
		&i.VoteCount,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDrawingByMatchID = `-- name: GetDrawingByMatchID :one
SELECT id, match_id, starter_id, finisher_id, doodle_strokes, finished_strokes, vote_count, created_at, finished_at FROM drawings
WHERE match_id = $1
`

func (q *Queries) GetDrawingByMatchID(ctx context.Context, matchID uuid.UUID) (Drawing, error) {
	row := q.db.QueryRowContext(ctx, getDrawingByMatchID, matchID)
	var i Drawing
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.StarterID,
		&i.FinisherID,
		&i.DoodleStrokes,
		&i.FinishedStrokes,
		&i.VoteCount,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateDrawingFinished = `-- name: UpdateDrawingFinished :exec
UPDATE drawings
SET finished_strokes = $1, finished_at = NOW()
WHERE match_id = $2
`

type UpdateDrawingFinishedParams struct {
	FinishedStrokes json.RawMessage
	MatchID         uuid.UUID
}

func (q *Queries) UpdateDrawingFinished(ctx context.Context, arg UpdateDrawingFinishedParams) error {
	_, err := q.db.ExecContext(ctx, updateDrawingFinished, arg.FinishedStrokes, arg.MatchID)
	return err
}
