// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, match_id)
VALUES ($1, $2)
`

type AddFavoriteParams struct {
	UserID  uuid.NullUUID
	MatchID uuid.UUID
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addFavorite, arg.UserID, arg.MatchID)
	return err
}

const getUserFavoritesMatchIDs = `-- name: GetUserFavoritesMatchIDs :many
SELECT match_id
FROM favorites
WHERE user_id = $1
`

func (q *Queries) GetUserFavoritesMatchIDs(ctx context.Context, userID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getUserFavoritesMatchIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var match_id uuid.UUID
		if err := rows.Scan(&match_id); err != nil {
			return nil, err
		}
		items = append(items, match_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1 AND match_id = $2
`

type RemoveFavoriteParams struct {
	UserID  uuid.NullUUID
	MatchID uuid.UUID
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeFavorite, arg.UserID, arg.MatchID)
	return err
}

const updateFavoritesCount = `-- name: UpdateFavoritesCount :exec
UPDATE matches
SET favorites_count = favorites_count + $1
WHERE id = $2
`

type UpdateFavoritesCountParams struct {
	FavoritesCount sql.NullInt32
	ID             uuid.UUID
}

func (q *Queries) UpdateFavoritesCount(ctx context.Context, arg UpdateFavoritesCountParams) error {
	_, err := q.db.ExecContext(ctx, updateFavoritesCount, arg.FavoritesCount, arg.ID)
	return err
}
