// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (id, starter_id, finisher_id, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, starter_id, finisher_id, created_at, finished_at, favorites_count
`

type CreateMatchParams struct {
	ID         uuid.UUID
	StarterID  uuid.NullUUID
	FinisherID uuid.NullUUID
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, createMatch, arg.ID, arg.StarterID, arg.FinisherID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.StarterID,
		&i.FinisherID,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.FavoritesCount,
	)
	return i, err
}

const deleteMatchByID = `-- name: DeleteMatchByID :exec
DELETE FROM matches WHERE id = $1
`

func (q *Queries) DeleteMatchByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMatchByID, id)
	return err
}

const getMostRecentMatches = `-- name: GetMostRecentMatches :many
SELECT id, starter_id, finisher_id, created_at, finished_at, favorites_count
FROM matches
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetMostRecentMatchesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetMostRecentMatches(ctx context.Context, arg GetMostRecentMatchesParams) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, getMostRecentMatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.StarterID,
			&i.FinisherID,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.FavoritesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
