// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (id, player1_id, player2_id, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING id, player1_id, player2_id, created_at, finished_at, favorites_count, drawing1_id, drawing2_id
`

type CreateMatchParams struct {
	ID        uuid.UUID
	Player1ID uuid.NullUUID
	Player2ID uuid.NullUUID
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, createMatch, arg.ID, arg.Player1ID, arg.Player2ID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Player1ID,
		&i.Player2ID,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.FavoritesCount,
		&i.Drawing1ID,
		&i.Drawing2ID,
	)
	return i, err
}

const deleteMatchByID = `-- name: DeleteMatchByID :exec
DELETE FROM matches WHERE id = $1
`

func (q *Queries) DeleteMatchByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMatchByID, id)
	return err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT 
    m.id AS match_id,
    m.created_at AS match_created_at,
    m.finished_at,
    m.favorites_count,
    m.player1_id,
    m.player2_id,
    d1.id AS drawing1_id,
    d1.user_id AS drawing1_user_id,
    d1.doodle_strokes AS drawing1_doodle,
    d1.finished_strokes AS drawing1_finished,
    d2.id AS drawing2_id,
    d2.user_id AS drawing2_user_id,
    d2.doodle_strokes AS drawing2_doodle,
    d2.finished_strokes AS drawing2_finished,
    COALESCE(u1.username, 'Deleted User') AS player1_username,
    COALESCE(u2.username, 'Deleted User') AS player2_username
FROM matches m
INNER JOIN drawings d1 ON d1.id = m.drawing1_id
INNER JOIN drawings d2 ON d2.id = m.drawing2_id
LEFT JOIN users u1 ON u1.id = m.player1_id
LEFT JOIN users u2 ON u2.id = m.player2_id
WHERE m.id = $1
`

type GetMatchByIDRow struct {
	MatchID          uuid.UUID
	MatchCreatedAt   time.Time
	FinishedAt       sql.NullTime
	FavoritesCount   sql.NullInt32
	Player1ID        uuid.NullUUID
	Player2ID        uuid.NullUUID
	Drawing1ID       uuid.UUID
	Drawing1UserID   uuid.NullUUID
	Drawing1Doodle   json.RawMessage
	Drawing1Finished json.RawMessage
	Drawing2ID       uuid.UUID
	Drawing2UserID   uuid.NullUUID
	Drawing2Doodle   json.RawMessage
	Drawing2Finished json.RawMessage
	Player1Username  string
	Player2Username  string
}

func (q *Queries) GetMatchByID(ctx context.Context, id uuid.UUID) (GetMatchByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMatchByID, id)
	var i GetMatchByIDRow
	err := row.Scan(
		&i.MatchID,
		&i.MatchCreatedAt,
		&i.FinishedAt,
		&i.FavoritesCount,
		&i.Player1ID,
		&i.Player2ID,
		&i.Drawing1ID,
		&i.Drawing1UserID,
		&i.Drawing1Doodle,
		&i.Drawing1Finished,
		&i.Drawing2ID,
		&i.Drawing2UserID,
		&i.Drawing2Doodle,
		&i.Drawing2Finished,
		&i.Player1Username,
		&i.Player2Username,
	)
	return i, err
}

const getMostRecentMatches = `-- name: GetMostRecentMatches :many
SELECT 
    m.id AS match_id,
    m.created_at AS match_created_at,
    m.finished_at,
    m.favorites_count,
    m.player1_id,
    m.player2_id,
    d1.id AS drawing1_id,
    d1.user_id AS drawing1_user_id,
    d1.doodle_strokes AS drawing1_doodle,
    d1.finished_strokes AS drawing1_finished,
    d2.id AS drawing2_id,
    d2.user_id AS drawing2_user_id,
    d2.doodle_strokes AS drawing2_doodle,
    d2.finished_strokes AS drawing2_finished,
    COALESCE(u1.username, 'Deleted User') AS player1_username,
    COALESCE(u2.username, 'Deleted User') AS player2_username
FROM matches m
LEFT JOIN drawings d1 ON d1.match_id = m.id
LEFT JOIN drawings d2 ON d2.match_id = m.id AND d2.id != d1.id
LEFT JOIN users u1 ON u1.id = m.player1_id
LEFT JOIN users u2 ON u2.id = m.player2_id
WHERE d1.id IS NOT NULL AND d2.id IS NOT NULL
  AND COALESCE(d1.user_id, '00000000-0000-0000-0000-000000000000') < COALESCE(d2.user_id, '00000000-0000-0000-0000-000000000000')
ORDER BY m.created_at DESC
LIMIT $1 OFFSET $2
`

type GetMostRecentMatchesParams struct {
	Limit  int32
	Offset int32
}

type GetMostRecentMatchesRow struct {
	MatchID          uuid.UUID
	MatchCreatedAt   time.Time
	FinishedAt       sql.NullTime
	FavoritesCount   sql.NullInt32
	Player1ID        uuid.NullUUID
	Player2ID        uuid.NullUUID
	Drawing1ID       uuid.NullUUID
	Drawing1UserID   uuid.NullUUID
	Drawing1Doodle   pqtype.NullRawMessage
	Drawing1Finished pqtype.NullRawMessage
	Drawing2ID       uuid.NullUUID
	Drawing2UserID   uuid.NullUUID
	Drawing2Doodle   pqtype.NullRawMessage
	Drawing2Finished pqtype.NullRawMessage
	Player1Username  string
	Player2Username  string
}

func (q *Queries) GetMostRecentMatches(ctx context.Context, arg GetMostRecentMatchesParams) ([]GetMostRecentMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMostRecentMatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMostRecentMatchesRow
	for rows.Next() {
		var i GetMostRecentMatchesRow
		if err := rows.Scan(
			&i.MatchID,
			&i.MatchCreatedAt,
			&i.FinishedAt,
			&i.FavoritesCount,
			&i.Player1ID,
			&i.Player2ID,
			&i.Drawing1ID,
			&i.Drawing1UserID,
			&i.Drawing1Doodle,
			&i.Drawing1Finished,
			&i.Drawing2ID,
			&i.Drawing2UserID,
			&i.Drawing2Doodle,
			&i.Drawing2Finished,
			&i.Player1Username,
			&i.Player2Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostRecentMatchesByUsername = `-- name: GetMostRecentMatchesByUsername :many
SELECT 
    m.id AS match_id,
    m.created_at AS match_created_at,
    m.finished_at,
    m.favorites_count,
    m.player1_id,
    m.player2_id,
    d1.id AS drawing1_id,
    d1.user_id AS drawing1_user_id,
    d1.doodle_strokes AS drawing1_doodle,
    d1.finished_strokes AS drawing1_finished,
    d2.id AS drawing2_id,
    d2.user_id AS drawing2_user_id,
    d2.doodle_strokes AS drawing2_doodle,
    d2.finished_strokes AS drawing2_finished,
    COALESCE(u1.username, 'Deleted User') AS player1_username,
    COALESCE(u2.username, 'Deleted User') AS player2_username
FROM matches m
LEFT JOIN drawings d1 ON d1.match_id = m.id
LEFT JOIN drawings d2 ON d2.match_id = m.id AND d2.id != d1.id
LEFT JOIN users u1 ON u1.id = m.player1_id
LEFT JOIN users u2 ON u2.id = m.player2_id
WHERE d1.id IS NOT NULL AND d2.id IS NOT NULL
  AND COALESCE(d1.user_id, '00000000-0000-0000-0000-000000000000') < COALESCE(d2.user_id, '00000000-0000-0000-0000-000000000000')
  AND (m.player1_id = $1 OR m.player2_id = $1)
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMostRecentMatchesByUsernameParams struct {
	Player1ID uuid.NullUUID
	Limit     int32
	Offset    int32
}

type GetMostRecentMatchesByUsernameRow struct {
	MatchID          uuid.UUID
	MatchCreatedAt   time.Time
	FinishedAt       sql.NullTime
	FavoritesCount   sql.NullInt32
	Player1ID        uuid.NullUUID
	Player2ID        uuid.NullUUID
	Drawing1ID       uuid.NullUUID
	Drawing1UserID   uuid.NullUUID
	Drawing1Doodle   pqtype.NullRawMessage
	Drawing1Finished pqtype.NullRawMessage
	Drawing2ID       uuid.NullUUID
	Drawing2UserID   uuid.NullUUID
	Drawing2Doodle   pqtype.NullRawMessage
	Drawing2Finished pqtype.NullRawMessage
	Player1Username  string
	Player2Username  string
}

func (q *Queries) GetMostRecentMatchesByUsername(ctx context.Context, arg GetMostRecentMatchesByUsernameParams) ([]GetMostRecentMatchesByUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, getMostRecentMatchesByUsername, arg.Player1ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMostRecentMatchesByUsernameRow
	for rows.Next() {
		var i GetMostRecentMatchesByUsernameRow
		if err := rows.Scan(
			&i.MatchID,
			&i.MatchCreatedAt,
			&i.FinishedAt,
			&i.FavoritesCount,
			&i.Player1ID,
			&i.Player2ID,
			&i.Drawing1ID,
			&i.Drawing1UserID,
			&i.Drawing1Doodle,
			&i.Drawing1Finished,
			&i.Drawing2ID,
			&i.Drawing2UserID,
			&i.Drawing2Doodle,
			&i.Drawing2Finished,
			&i.Player1Username,
			&i.Player2Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalMatches = `-- name: GetTotalMatches :one
SELECT COUNT(DISTINCT m.id)
FROM matches m
LEFT JOIN drawings d1 ON d1.match_id = m.id
LEFT JOIN drawings d2 ON d2.match_id = m.id AND d2.id != d1.id
WHERE d1.id IS NOT NULL AND d2.id IS NOT NULL
  AND COALESCE(d1.user_id, '00000000-0000-0000-0000-000000000000') < COALESCE(d2.user_id, '00000000-0000-0000-0000-000000000000')
`

func (q *Queries) GetTotalMatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalMatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalMatchesByUsername = `-- name: GetTotalMatchesByUsername :one
SELECT COUNT(DISTINCT m.id)
FROM matches m
LEFT JOIN drawings d1 ON d1.match_id = m.id
LEFT JOIN drawings d2 ON d2.match_id = m.id AND d2.id != d1.id
WHERE d1.id IS NOT NULL AND d2.id IS NOT NULL
  AND COALESCE(d1.user_id, '00000000-0000-0000-0000-000000000000') < COALESCE(d2.user_id, '00000000-0000-0000-0000-000000000000')
  AND (m.player1_id = $1 OR m.player2_id = $1)
`

func (q *Queries) GetTotalMatchesByUsername(ctx context.Context, player1ID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalMatchesByUsername, player1ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateMatch = `-- name: UpdateMatch :exec
UPDATE matches
SET 
    drawing1_id = $1,
    drawing2_id = $2
WHERE id = $3
`

type UpdateMatchParams struct {
	Drawing1ID uuid.NullUUID
	Drawing2ID uuid.NullUUID
	ID         uuid.UUID
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) error {
	_, err := q.db.ExecContext(ctx, updateMatch, arg.Drawing1ID, arg.Drawing2ID, arg.ID)
	return err
}

const upgradeGuestToUser = `-- name: UpgradeGuestToUser :exec
UPDATE users
SET 
    username = $1,
    is_guest = false,
    password_hash = $2
WHERE id = $3 AND is_guest = true
`

type UpgradeGuestToUserParams struct {
	Username     string
	PasswordHash sql.NullString
	ID           uuid.UUID
}

func (q *Queries) UpgradeGuestToUser(ctx context.Context, arg UpgradeGuestToUserParams) error {
	_, err := q.db.ExecContext(ctx, upgradeGuestToUser, arg.Username, arg.PasswordHash, arg.ID)
	return err
}
