// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Drawing struct {
	ID              uuid.UUID
	MatchID         uuid.UUID
	UserID          uuid.NullUUID
	DoodleStrokes   json.RawMessage
	FinishedStrokes json.RawMessage
	VoteCount       sql.NullInt32
	CreatedAt       sql.NullTime
}

type Match struct {
	ID         uuid.UUID
	StarterID  uuid.NullUUID
	FinisherID uuid.NullUUID
	CreatedAt  sql.NullTime
	FinishedAt sql.NullTime
}

type Session struct {
	Token     string
	CreatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	PasswordHash   sql.NullString
	CreatedAt      sql.NullTime
	LastActiveAt   sql.NullTime
	IsGuest        sql.NullBool
	ExpiresAt      sql.NullTime
	ProfileStrokes pqtype.NullRawMessage
}

type Vote struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	DrawingID uuid.UUID
	CreatedAt sql.NullTime
}
