// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Drawing struct {
	ID              uuid.UUID
	MatchID         uuid.UUID
	StarterID       uuid.UUID
	FinisherID      uuid.UUID
	DoodleStrokes   json.RawMessage
	FinishedStrokes json.RawMessage
	VoteCount       sql.NullInt32
	CreatedAt       sql.NullTime
	FinishedAt      sql.NullTime
}

type Match struct {
	ID         uuid.UUID
	StarterID  uuid.UUID
	FinisherID uuid.UUID
	CreatedAt  sql.NullTime
	FinishedAt sql.NullTime
}

type Session struct {
	Token     string
	CreatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	LastActiveAt sql.NullTime
}

type Vote struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DrawingID uuid.UUID
	CreatedAt sql.NullTime
}
