// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Drawing struct {
	ID              uuid.UUID
	MatchID         uuid.UUID
	UserID          uuid.NullUUID
	DoodleStrokes   json.RawMessage
	FinishedStrokes json.RawMessage
	CreatedAt       sql.NullTime
}

type Favorite struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	CreatedAt sql.NullTime
	MatchID   uuid.UUID
}

type Match struct {
	ID             uuid.UUID
	Player1ID      uuid.NullUUID
	Player2ID      uuid.NullUUID
	CreatedAt      sql.NullTime
	FinishedAt     sql.NullTime
	FavoritesCount sql.NullInt32
	Drawing1ID     uuid.NullUUID
	Drawing2ID     uuid.NullUUID
}

type Session struct {
	Token     string
	CreatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash sql.NullString
	CreatedAt    sql.NullTime
	LastActiveAt sql.NullTime
	IsGuest      sql.NullBool
	ExpiresAt    sql.NullTime
	AvatarPath   sql.NullString
	Bio          string
}
