// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports(reporter_id, match_id, url, reported_at) 
VALUES ($1, $2, $3, $4)
RETURNING id, reporter_id, match_id, url, reported_at
`

type CreateReportParams struct {
	ReporterID uuid.UUID
	MatchID    uuid.UUID
	Url        string
	ReportedAt time.Time
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ReporterID,
		arg.MatchID,
		arg.Url,
		arg.ReportedAt,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.MatchID,
		&i.Url,
		&i.ReportedAt,
	)
	return i, err
}

const deleteReportByID = `-- name: DeleteReportByID :exec
DELETE FROM reports WHERE id = $1
`

func (q *Queries) DeleteReportByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReportByID, id)
	return err
}
