// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, created_at, user_id, expires_at)
VALUES (
	$1,
	NOW(),
	$2,
	$3
)
RETURNING token, created_at, user_id, expires_at
`

type CreateSessionParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UserID,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, token)
	return err
}

const getUserByCookie = `-- name: GetUserByCookie :one
SELECT u.id, u.username, u.is_guest
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = $1 AND s.expires_at > NOW()
`

type GetUserByCookieRow struct {
	ID       uuid.UUID
	Username string
	IsGuest  sql.NullBool
}

func (q *Queries) GetUserByCookie(ctx context.Context, token string) (GetUserByCookieRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByCookie, token)
	var i GetUserByCookieRow
	err := row.Scan(&i.ID, &i.Username, &i.IsGuest)
	return i, err
}
