// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createGuest = `-- name: CreateGuest :one
INSERT INTO users (username, is_guest, expires_at, avatar_path)
VALUES (
    $1,
    true,
    NOW() + INTERVAL '24 hours',
    $2
)
RETURNING id, username, avatar_path
`

type CreateGuestParams struct {
	Username   string
	AvatarPath sql.NullString
}

type CreateGuestRow struct {
	ID         uuid.UUID
	Username   string
	AvatarPath sql.NullString
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (CreateGuestRow, error) {
	row := q.db.QueryRowContext(ctx, createGuest, arg.Username, arg.AvatarPath)
	var i CreateGuestRow
	err := row.Scan(&i.ID, &i.Username, &i.AvatarPath)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, created_at, last_active_at, is_guest, avatar_path)
VALUES (
    $1,
    $2,
    $3,
	NOW(),
    NOW(),
    false,
    $4
)
RETURNING id, username, email, created_at, avatar_path
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash sql.NullString
	AvatarPath   sql.NullString
}

type CreateUserRow struct {
	ID         uuid.UUID
	Username   string
	Email      string
	CreatedAt  time.Time
	AvatarPath sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.AvatarPath,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.AvatarPath,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, last_active_at, is_guest, expires_at, avatar_path, bio
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.IsGuest,
		&i.ExpiresAt,
		&i.AvatarPath,
		&i.Bio,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, last_active_at, is_guest, expires_at, avatar_path, bio
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.IsGuest,
		&i.ExpiresAt,
		&i.AvatarPath,
		&i.Bio,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, created_at, last_active_at, is_guest, expires_at, avatar_path, bio
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.IsGuest,
		&i.ExpiresAt,
		&i.AvatarPath,
		&i.Bio,
	)
	return i, err
}

const updateAvatar = `-- name: UpdateAvatar :exec
UPDATE users
SET avatar_path = $1
WHERE id = $2
`

type UpdateAvatarParams struct {
	AvatarPath sql.NullString
	ID         uuid.UUID
}

func (q *Queries) UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateAvatar, arg.AvatarPath, arg.ID)
	return err
}

const updateLastActive = `-- name: UpdateLastActive :exec
UPDATE users
SET last_active_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastActive, id)
	return err
}
