// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addVote = `-- name: AddVote :exec
INSERT INTO votes (user_id, drawing_id)
VALUES ($1, $2)
`

type AddVoteParams struct {
	UserID    uuid.NullUUID
	DrawingID uuid.UUID
}

func (q *Queries) AddVote(ctx context.Context, arg AddVoteParams) error {
	_, err := q.db.ExecContext(ctx, addVote, arg.UserID, arg.DrawingID)
	return err
}

const getUserVotedDrawingIDs = `-- name: GetUserVotedDrawingIDs :many
SELECT drawing_id
FROM votes
WHERE user_id = $1
`

func (q *Queries) GetUserVotedDrawingIDs(ctx context.Context, userID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getUserVotedDrawingIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var drawing_id uuid.UUID
		if err := rows.Scan(&drawing_id); err != nil {
			return nil, err
		}
		items = append(items, drawing_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeVote = `-- name: RemoveVote :exec
DELETE FROM votes
WHERE user_id = $1 AND drawing_id = $2
`

type RemoveVoteParams struct {
	UserID    uuid.NullUUID
	DrawingID uuid.UUID
}

func (q *Queries) RemoveVote(ctx context.Context, arg RemoveVoteParams) error {
	_, err := q.db.ExecContext(ctx, removeVote, arg.UserID, arg.DrawingID)
	return err
}

const updateVoteCount = `-- name: UpdateVoteCount :exec
UPDATE drawings
SET vote_count = vote_count + $1
WHERE id = $2
`

type UpdateVoteCountParams struct {
	VoteCount sql.NullInt32
	ID        uuid.UUID
}

func (q *Queries) UpdateVoteCount(ctx context.Context, arg UpdateVoteCountParams) error {
	_, err := q.db.ExecContext(ctx, updateVoteCount, arg.VoteCount, arg.ID)
	return err
}
